#!/usr/bin/env bash

# Install native apps
run_apps() {
	#utils
	brew cask install alfred
	brew cask install cakebrew
	brew cask install launchcontrol

	# dev
	brew cask install couleurs
	brew cask install cyberduck
	brew cask install firefox
	brew cask install github
	brew cask install google-chrome
	brew cask install imageoptim
	brew cask install ksdiff # Kaleidoscope command line
	brew cask install macdown
	brew cask install visual-studio-code

	# colorpickers
	brew cask install colorpicker-materialdesign colorpicker-propicker colorpicker-skalacolor
}
