#!/usr/bin/env bash

# Install native apps
run_apps() {
	#utils
	brew install --cask alfred
	brew install --cask cakebrew
	brew install --cask launchcontrol

	# dev
	brew install --cask couleurs
	brew install --cask cyberduck
	brew install --cask firefox
	brew install --cask github
	brew install --cask google-chrome
	brew install --cask imageoptim
	brew install --cask ksdiff # Kaleidoscope command line
	brew install --cask macdown
	brew install --cask visual-studio-code

	# colorpickers
	brew install --cask colorpicker-materialdesign colorpicker-propicker colorpicker-skalacolor
}
