#!/usr/bin/env bash

# Install command-line tools using Homebrew
run_brew() {

	# Make sure we’re using the latest Homebrew
	brew update

	# Taps
	brew tap homebrew/services
	brew tap caskroom/cask
	brew tap caskroom/fonts

	# Install GNU core utilities (those that come with OS X are outdated)
	brew install coreutils

	# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
	brew install findutils
	brew install ngrep

	# Install Bash 4
	brew install bash

	# Completions
	brew install bash-completion2 gem-completion docker-completion launchctl-completion wpcli-completion zsh-completions

	# Install more recent versions of some OS X tools
	brew install vim --override-system-vi
	brew install grep
	brew install screen

	#Python
	brew install python3

	# Install wget with IRI support
	brew install wget --with-iri

	# Install useful binaries
	brew install ack
	brew install gpg
	brew install thefuck
	brew install git
	brew install hub
	brew install httpie
	brew install jq
	brew install imagemagick --with-webp
	brew install lame
	brew install node
	brew install nvm
	brew install rename
	brew install tree
	brew install zsh
	brew install --cask unshaky

	# Install code review tools
	brew tap codeclimate/formulae
	brew install codeclimate

	# Install git tools
	brew install hub
	brew install tig
	brew install git-extras

	# Install other tools
	brew install watchman

	#brew link openssl --force

	# Remove outdated versions from the cellar
	brew cleanup
}
